### ISSUE TITLE
Build fails due to missing dependencies

### ISSUE THREAD

**Issue by niner** [potyl/perl-Gtk3-WebKit#1]
I tried to install Gtk3::WebKit (as dependency for WWW::WebKit) on a fresh perlbrew installation.

cpanp fails to even start installation:

Running [/home/nine/perl5/perlbrew/perls/perl-5.16.2/bin/perl -e use strict; BEGIN { my $old = select STDERR; $|++; select $old; $|++; $0 = shift(@ARGV); my $rv = do($0); die $@ if $@; } /home/nine/.cpanplus/5.16.2/build/Gtk3-WebKit-0.02/Makefile.PL]...
Use of uninitialized value $makestat in numeric lt (<) at /home/nine/perl5/perlbrew/perls/perl-5.16.2/lib/5.16.2/CPANPLUS/Dist/MM.pm line 411.
Use of uninitialized value $makestat in subtraction (-) at /home/nine/perl5/perlbrew/perls/perl-5.16.2/lib/5.16.2/CPANPLUS/Dist/MM.pm line 412.
[ERROR] File '/home/nine/.cpanplus/5.16.2/build/Gtk3-WebKit-0.02/Makefile' is not readable or does not exist

Key 'file' (/home/nine/.cpanplus/5.16.2/build/Gtk3-WebKit-0.02/Makefile) is of invalid type for 'CPANPLUS::Dist::MM::_find_prereqs' provided by CPANPLUS::Dist::MM::prepare at /home/nine/perl5/perlbrew/perls/perl-5.16.2/lib/5.16.2/CPANPLUS/Module.pm line 823.
[ERROR] Unable to scan '/home/nine/.cpanplus/5.16.2/build/Gtk3-WebKit-0.02/Makefile' for prereqs

Trying to install with good old cpan then fails to install all required prerequisites:

  CPAN.pm: Building P/PO/POTYL/Gtk3-WebKit-0.02.tar.gz

Checking if your kit is complete...
Looks good
MakeMaker FATAL: prerequisites not found.
    Glib::Object::Introspection not installed

Please install these modules first and rerun 'perl Makefile.PL'.
Warning: No success on command[/home/nine/perl5/perlbrew/perls/perl-5.16.2/bin/perl Makefile.PL]
  POTYL/Gtk3-WebKit-0.02.tar.gz
  /home/nine/perl5/perlbrew/perls/perl-5.16.2/bin/perl Makefile.PL -- NOT OK

cpan does not seem to try installing the dependency. I suspect, it's because Makefile.PL returns a different status than usual. All other MakeMaker Makefile.PLs I've seen have WriteMakefile as their last command.

Even when installing Glib::Object::Introspection manually, there's still a missing dependency: Gtk3
After installing this manually, installation worked for me.

**Comment by potyl** [comment]
In theory Gtk3.pm is not a dependency of Gtk3/WebKit.pm now that the module uses Glib::Object::Introspection, Gtk3::WebKit can loaded with Gtk3. Although it will be not as useful.

I think that if Gtk3 is missing it's because WWW::WebKit needs it.

> All other MakeMaker Makefile.PLs I've seen have WriteMakefile as their last command.

Yeah. I should definitely use that as the return value.

**Comment by niner** [comment]
Gtk3::WebKit may in theory work without Gtk3, but it's tests for sure don't:

t/webkit.t .. Can't locate Gtk3.pm in @INC (@INC contains: /home/nine/.cpan/build/Gtk3-WebKit-0.02-HHq_3Y/blib/lib /home/nine/.cpan/build/Gtk3-WebKit-0.02-HHq_3Y/blib/arch /home/nine/work/lib /home/nine/work/lib /home/nine/perl5/perlbrew/perls/perl-5.16.2/lib/site_perl/5.16.2/x86_64-linux /home/nine/perl5/perlbrew/perls/perl-5.16.2/lib/site_perl/5.16.2 /home/nine/perl5/perlbrew/perls/perl-5.16.2/lib/5.16.2/x86_64-linux /home/nine/perl5/perlbrew/perls/perl-5.16.2/lib/5.16.2 .) at t/webkit.t line 10.

**Comment by potyl** [comment]
I need to make that Gtk3 tests optional.

Thanks for reporting this.

**Comment by potyl** [comment]
I made Gtk3 a dependency of Gtk3::WebKit. This should make things easier for everyone.
