### ISSUE TITLE
Build failure; Ubuntu 12.04 LTS; perl v5.16.3; perlbrew; cpanm

### ISSUE THREAD

**Issue by minty** [potyl/perl-Gtk3-WebKit#2]
(Module looks very useful -- thanks for your work on it -- sorry to be filing a bug, if I'm doing something stupid, could you point me in the right direction? :)

(Update: this is a headless server -- is this _supposed_ to work headless?  That might be the "me being stupid" bit?)

Installed Perl v5.16.3 via perlbrew: OK

aptitude update && aptitude safe-upgrade

found I needed these:
aptitude install libglib2.0-0 libglib2.0-dev libgtk-3-dev libgirepository1.0-dev

Trying to "cpanm WWW::WebKit"

...
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.63_02)
Checking if you have Gtk3 0 ... Yes (0.009)
Checking if you have Glib::Object::Introspection 0 ... Yes (0.015)
Building and testing Gtk3-WebKit-0.03
cp lib/Gtk3/WebKit.pm blib/lib/Gtk3/WebKit.pm
Manifying blib/man3/Gtk3::WebKit.3
PERL_DL_NONLAZY=1 /home/minty/perl5/perlbrew/perls/perl-5.16.2/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/_.t
*_\* Cannot use generic signal marshallers for signal insert-text of Gtk3::Editable unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly
**\* Cannot use generic signal marshallers for signal response of Gtk3::Dialog unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly
**\* Cannot use generic signal marshallers for signal response of Gtk3::InfoBar unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly

(webkit.t:17298): Gtk-WARNING **: cannot open display:
t/webkit.t ..
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run
Suggestions?

**Comment by potyl** [comment]
Hi,

It seems the installation failed at the unit tests. Currently the gtk webkit port is not headless, you need an X display. Gtk3 won't load without one. The good thing is that you can use a framebuffer display, so you don't need to have an X server running.

Try to run the cpanm command with:

xvfb-run --server-args="-screen 0 1024x768x24" cpanm Gtk3::WebKit

You will need to install xvfb-run which is provided by the debian package [xvfb](http://packages.debian.org/sid/xvfb).

PS: you shouldn't be using WWW::WebKit, that's an old package name.

**Comment by minty** [comment]
Ahh :)  thanks for the pointers, sadly, so far, no joy -- but progress, I think ...

> xvfb-run --server-args="-screen 0 1024x768x24" cpanm Gtk3::WebKit

Checking if you have Glib::Object::Introspection 0 ... Yes (0.015)
Building and testing Gtk3-WebKit-0.03
cp lib/Gtk3/WebKit.pm blib/lib/Gtk3/WebKit.pm
Manifying blib/man3/Gtk3::WebKit.3
PERL_DL_NONLAZY=1 /home/minty/perl5/perlbrew/perls/perl-5.16.2/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/_.t
*_\* Cannot use generic signal marshallers for signal insert-text of Gtk3::Editable unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly
**\* Cannot use generic signal marshallers for signal response of Gtk3::Dialog unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly
**\* Cannot use generic signal marshallers for signal response of Gtk3::InfoBar unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly

 #   Failed test 'use Gtk3::WebKit;'
 #   at t/webkit.t line 14.
 #     Tried to use 'Gtk3::WebKit'.
 #     Error:  Typelib file for namespace 'WebKit', version '3.0' not found at /home/minty/perl5/perlbrew/perls/perl-5.16.2/lib/site_perl/5.16.3/i686-linux/Glib/Object/Introspection.pm line 92.
 # BEGIN failed--compilation aborted at (eval 4) line 2.
Can't locate object method "new" via package "Gtk3::WebKit::WebView" (perhaps you forgot to load "Gtk3::WebKit::WebView"?) at t/webkit.t line 19.

I tried adding the "use Gtk3::WebKit::WebView" ... but unless I'm being stupid (which is entirely likely), I can't see any Gtk3::WebKit::WebView in the package?

wget http://search.cpan.org/CPAN/authors/id/P/PO/POTYL/Gtk3-WebKit-0.03.tar.gz
unbundle, etc

grep -ir WebView *
blib/man3/Gtk3::WebKit.3:&        my $view = Gtk3::WebKit::WebView->new();
blib/lib/Gtk3/WebKit.pm:        my $view = Gtk3::WebKit::WebView->new();
examples/browser.pl:    my $view = Gtk3::WebKit::WebView->new();
lib/Gtk3/WebKit.pm:     my $view = Gtk3::WebKit::WebView->new();
t/webkit.t:use Gtk3::WebKit::WebView;
t/webkit.t:    use_ok('Gtk3::WebKit::WebView');
t/webkit.t:    my $view = Gtk3::WebKit::WebView->new();
t/webkit.t:    isa_ok($view, 'Gtk3::WebKit::WebView');

> PS: you shouldn't be using WWW::WebKit, that's an old package name.

What should it be?  Test::WWW::WebKit?  I could rustle up a patch to the POD in the older module if you are willing?  At least, I didn't see anything in the POD pointing me to a newer name ... Is this the right repo to be forking from https://github.com/niner/WWW-WebKit or are there two WWW::WebKits floating around? :)

**Comment by potyl** [comment]
Disregard my WWW-WebKit comment, I just saw that it's a different perl module. In the past I my Gtk3::WebKit used to be in a different namespace. I though that it was WWW::WebKit, this is not the case. You can use WWW::WebKit.

Which Linux system are you using?

Since Gtk3::WebKit is a simple 'pure' perl module. I would suggest that you don't use cpanm.
Download that .tar.gz from cpan:

```
wget http://search.cpan.org/CPAN/authors/id/P/PO/POTYL/Gtk3-WebKit-0.03.tar.gz
```

Then do:

```
tar xf Gtk3-WebKit-0.03.tar.gz
cd Gtk3-WebKit-0.03
perl Makefile.PL 
xvfb-run --server-args="-screen 0 1024x768x24" make test
sudo make install
```

This way you would force the unit test to run with the frame buffer. If the unit tests are still not running with the framebuffer try this:

```
xvfb-run --server-args="-screen 0 1024x768x24" perl -Mblib t/webkit.t
```

I hope that this helps.

**Comment by minty** [comment]
Ubuntu 12.04, fully patched and up to date today.

Sorry, I did try downloading the module on it's own as you suggested, but I've re-done it again now, output below

wget http://search.cpan.org/CPAN/authors/id/P/PO/POTYL/Gtk3-WebKit-0.03.tar.gz
tar xvf Gtk3-WebKit-0.03.tar.gz 
cd Gtk3-WebKit-0.03/

§ perl Makefile.PL 
Checking if your kit is complete...
Looks good
Writing Makefile for Gtk3::WebKit
Writing MYMETA.yml and MYMETA.json

§ xvfb-run --server-args="-screen 0 1024x768x24" make test
cp lib/Gtk3/WebKit.pm blib/lib/Gtk3/WebKit.pm
PERL_DL_NONLAZY=1 /home/minty/perl5/perlbrew/perls/perl-5.16.2/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/_.t
t/webkit.t .. *_\* Cannot use generic signal marshallers for signal insert-text of Gtk3::Editable unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly
**\* Cannot use generic signal marshallers for signal response of Gtk3::Dialog unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly
**\* Cannot use generic signal marshallers for signal response of Gtk3::InfoBar unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly
t/webkit.t .. 1/? 
 #   Failed test 'use Gtk3::WebKit;'
 #   at t/webkit.t line 14.
 #     Tried to use 'Gtk3::WebKit'.
 #     Error:  Typelib file for namespace 'WebKit', version '3.0' not found at /home/minty/perl5/perlbrew/perls/perl-5.16.2/lib/site_perl/5.16.3/i686-linux/Glib/Object/Introspection.pm line 92.
 # BEGIN failed--compilation aborted at (eval 4) line 2.
Can't locate object method "new" via package "Gtk3::WebKit::WebView" (perhaps you forgot to load "Gtk3::WebKit::WebView"?) at t/webkit.t line 19.
 # Looks like you failed 1 test of 1.
 # Looks like your test exited with 255 just after 1.
t/webkit.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 

Test Summary Report

---

t/webkit.t (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.06 cusr  0.01 csys =  0.09 CPU)
Result: FAIL
Failed 1/1 test programs. 1/1 subtests failed.
make: **\* [test_dynamic] Error 255

**Comment by minty** [comment]
§ xvfb-run --server-args="-screen 0 1024x768x24" perl -Mblib t/webkit.t
**\* Cannot use generic signal marshallers for signal insert-text of Gtk3::Editable unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly
**\* Cannot use generic signal marshallers for signal response of Gtk3::Dialog unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly
**\* Cannot use generic signal marshallers for signal response of Gtk3::InfoBar unless gobject-introspection >= 1.33.10; any handlers connected to the signal might thus be invoked incorrectly
not ok 1 - use Gtk3::WebKit;
 #   Failed test 'use Gtk3::WebKit;'
 #   at t/webkit.t line 14.
 #     Tried to use 'Gtk3::WebKit'.
 #     Error:  Typelib file for namespace 'WebKit', version '3.0' not found at /home/minty/perl5/perlbrew/perls/perl-5.16.2/lib/site_perl/5.16.3/i686-linux/Glib/Object/Introspection.pm line 92.
 # BEGIN failed--compilation aborted at (eval 4) line 2.
Can't locate object method "new" via package "Gtk3::WebKit::WebView" (perhaps you forgot to load "Gtk3::WebKit::WebView"?) at t/webkit.t line 19.
1..1
 # Looks like you failed 1 test of 1.
 # Looks like your test exited with 255 just after 1.

**Comment by potyl** [comment]
I installed an Ubuntu 12.04 server KVM and I tried to installed the software.

>  Error: Typelib file for namespace 'WebKit', version '3.0' not found at /home/minty/perl5/perlbrew/perls/perl-5.16.2/lib/site_perl/5.16.3/i686-linux/Glib/Object/Introspection.pm line 92.

This means that you need to install the 'gir' package for webkit:

```
sudo apt-get install gir1.2-webkit-3.0
```

Then run the unit tests with the frame buffer as I described earlier:

```
xvfb-run --server-args="-screen 0 1024x768x24" make test
```

You will still have a lot of warnings about gobject introspection, you might need to upgrade some libraries.

Let me know if it helps.

**Comment by minty** [comment]
"All tests successful".

Thanks so much for your help.

I'd be happy to submit some patches to the POD along these lines -- if nothing else, it strikes me as a possibly useful test to check for $DISPLAY being set early and explicitly bailing out if not, with a more useful error?

However, I'm a little out of my depth in this area (as is probably quite clear!), so let me know if that would be something you'd like / think worth-while and I will have a go and send you a pull request.

I'm not sure if adding Debian/Ubuntu specific things to the POD is a good idea.  I'm not sure how one states the non-Perl dependencies in the perl Makefile.PL ?

Thus, for now, I offer this as a small contribution to say thanks for all your help :)

http://blogs.perl.org/users/minty/2013/03/gtk3webkit-on-ubuntu.html

**Comment by potyl** [comment]
I'm glad that the module works now on your server. Remember to run your programs with the frame buffer X server

About the documentation, I think that the POD is the best place to put it. If we add this to the github wiki users of CPAN might not see it.

If you do a pull request with documentation improvements I will be glad to merge it. If you do please put this under a sub section dedicated for installation.

Ex:
    =head1 INSTALLATION
    =head2 Debian based systems (Ubuntu)
    To install this module under a debian base system, blah, blah, blah

I do need to adjust the unit tests. Gtk3 has no problem running the unit tests without an X server, I believe that it skips them.

Also detecting if the GIR file is installed would be nice.

Thanks for the feedback!

**Comment by minty** [comment]
https://github.com/potyl/perl-Gtk3-WebKit/commit/e3ac0517f2cfc3db2eb755a6597ca419582839d8
